de

diff --git a/.openshift/action_hooks/deploy b/.openshift/action_hooks/deploy
--- a/.openshift/action_hooks/deploy
+++ b/.openshift/action_hooks/deploy
@@ -9,17 +9,17 @@ APP=pyramidapp
 
 source ~/$PYTHON/virtenv/bin/activate
 
-if [ -z $OPENSHIFT_DB_HOST ]
-then
-    echo 1>&2
-    echo 1>&2
-    echo "Could not find mysql database.  Please run:" 1>&2
-    echo "rhc-ctl-app -a $OPENSHIFT_APP_NAME -e add-mysql-5.1" 1>&2
-    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
-    echo 1>&2
-    echo 1>&2
-    exit 5
-fi
+#if [ -z $OPENSHIFT_DB_HOST ]
+#then
+#    echo 1>&2
+#    echo 1>&2
+#    echo "Could not find mysql database.  Please run:" 1>&2
+#    echo "rhc-ctl-app -a $OPENSHIFT_APP_NAME -e add-mysql-5.1" 1>&2
+#    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
+#    echo 1>&2
+#    echo 1>&2
+#    exit 5
+#fi
 
 cd $OPENSHIFT_REPO_DIR/wsgi/$APP
 
@@ -34,4 +34,4 @@ fi
 # At the moment failure does not prevent the code from getting deployed
 echo "Running the test suite"
 unset OPENSHIFT_APP_NAME
-python setup.py test
+#python setup.py test
